[package]
name = "tufa_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# yew = "0.19"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
# http = "0.2.6"
wasm-logger = "0.2.0"
log = "0.4.6"
reqwasm = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
# serde = "1.0"
# futures = "0.3.21"
# gloo-net = "0.2.0"
#
# serde_json = "1.0"